[pytest]
filterwarnings =
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning

[tool.pytest.ini_options]
filterwarnings = ["ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning"]
