name: ci-feature
# la CI se déclenche lorsque le push est sur une branche commençant par feature/..

on:
  push:
    branches:
      - "feature/**"
 
jobs:
  # la job s'appelle fast-checks / La job fast-checks s’exécute sur Ubuntu et contient plusieurs étapes à exécuter dans l’ordre.
  fast-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements-dev.txt
      - name: Lint rapide # Le Lint = vérification automatique de la qualité et de certaines erreurs du code.
        run: | 
          pip install flake8 
          flake8 app tests --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Tests unitaires  # les tests unitaire exécutent tous les tests qui se trouvent dans le dossier tests/units.
        run: |
          export PYTHONPATH=$(pwd)
          pytest tests/units -v